# Generated by Django 5.0.4 on 2024-05-02 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_carinventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carinventory',
            options={'ordering': ['-created_at']},
        ),
    ]
